### ISSUE TITLE
What is the status?

### ISSUE THREAD

**Issue by raphant** [lukegarbutt/RunescapeBots#12]
Hey, I am interested in using this. Have you used this any as of recent?

**Comment by lukegarbutt** [comment]
I haven't used it in a long time, and it's likely it won't work as is, but if you know anything about python or how it works you should be able to get it running, check out my YouTube videos on it where I explain how it works if you want to try and fix it :)

On 1 May 2018 22:58, en-lofty <notifications@github.com> wrote:

Hey, I am interested in using this. Have you used this any as of recent?

**Comment by raphant** [comment]
Nice, I am currently trying exploring the pyautogui to get familiar with some of the functionality. That realmouse.py is really a work of art :+1: 

Awesome work btw, I'll be working on this for a few days

**Comment by lukegarbutt** [comment]
Haha thanks man, let me know how it goes :)

On 2 May 2018 02:46, en-lofty <notifications@github.com> wrote:

Nice, I am currently trying exploring the pyautogui to get familiar with some of the functionality. That realmouse.py is really a work of art 👍

Awesome work btw, I'll be working on this for a few days

**Comment by Zetta-Zerena** [comment]
Holy Shit I need this! Is it still down? I'm just starting to learn to program and python is gonna be my first to learn I can't tween it like you said :(

**Comment by BenLand100** [comment]
> Nice, I am currently trying exploring the pyautogui to get familiar with some of the functionality. That realmouse.py is really a work of art +1
> 
> Awesome work btw, I'll be working on this for a few days

Unfortunately realmouse.py was ported without attribution from GPL code either from SRL https://github.com/SRL/SRL/blob/master/shared/mouse.simba#L100 or SMART https://github.com/BenLand100/SMART/blob/master/src/EventNazi.java#L201 which were the original references.

**Comment by lukegarbutt** [comment]
Hey man, feel free to add the correct references to the repo, I had no idea where the code was pulled from as that part wasn't done by me.
